spring:
  profiles:
    active: local
  rabbitmq:
    host: ${AMQP_HOST}
    port: ${AMQP_PORT}
    username: ${AMQP_USER}
    password: ${AMQP_PASS}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
        acknowledge-mode: manual # default: auto
    publisher-returns: true
